### ISSUE TITLE
Search implementation

### ISSUE THREAD

**Issue by gchp** [kisielk/vigo#20]
This is a question more than an issue. I'm thinking that having search functionality would be a good next step for the editor, and have an implementation question.

I know that there is the concept of a mode, and also an overlay, so I'm wondering if it would be correct to implement search as both a mode and an overlay. It will need the capture the cursor (as an overlay) in order to allow the search term to be entered, then the navigating of search results will be contained in the mode (pressing `n` to go to next occurrence etc).

Does that sound somewhat sensible? Wanted to get some thoughts before proceeding.

**Comment by dtcaciuc** [comment]
I think this makes sense. mode/command.go works the same way

**Comment by kisielk** [comment]
Usually `n` is just a normal mode command though.

**Comment by kisielk** [comment]
In other words, I'd prefer not to have a separate mode for searching, but rather just a search command in normal mode, triggered by `/`. Then the search query is saved in the editor and pushing `n` in normal mode goes to the next occurrence after the cursor.

**Comment by dtcaciuc** [comment]
On the other hand, you can have a separate search mode which is active while you're typing. As you press enter, it goes back to normal mode and passes in search results to it. Then you can jump through search results in that normal mode by pressing 'n'.

**Comment by gchp** [comment]
If we are to just store the search term in the normal mode, then way pressing `n` or `N` will search for the last search term. We will still need to create an overlay in order to capture the cursor and to allow the search term to be entered.

**Comment by gchp** [comment]
Would it make more sense to store the last search term on the editor, rather than in the normal mode? Should search terms persist across changing modes?

**Comment by kisielk** [comment]
I think the editor makes more sense. It would allow implementing things like using the last searched for term in a command mode command, etc.

**Comment by gchp** [comment]
Cool. I'll put something together on this and submit a PR. We can use that as a base then to see how you want it to work

**Comment by kisielk** [comment]
Sounds good :+1:
