### ISSUE TITLE
Configuration options

### ISSUE THREAD

**Issue by gchp** [kisielk/vigo#33]
Is it too early to start looking at how to specify external configuration? The vigo equivalent of a `.vimrc`?

Not sure if you guys have thought about this already. Personally, I think it would be cool to have some kind of python API that would allow certain parts of the editor to be customized. For instance, to bind a key:

``` python
from vigo.keys import bind_key
from vigo.commands.movement import center_line

bind_key("CtrlL", center_line)
```

Or something simpler like a JSON file, which would be more like how Sublime Text does it.

``` json
{"keys": ["CtrlL"], "command": "center_line"}
```

The idea being then that either the file is evaluated when the editor is started, or if JSON then just loaded into memory, and when it comes to handle an event, we add an extra step which would first check the loaded config options, otherwise it will do whatever the default is.

These are just ideas, wanted to get some thoughts and opinions. If you've already thought about this, what way had you planned?

**Comment by kisielk** [comment]
I don't have any plans for configuration at this point. I'd prefer to keep it to a minimum overall, but I guess we will need something eventually, I just think it's too early to think about just yet. I especially want to avoid getting in to anything like vimscript.

**Comment by gchp** [comment]
No worries, I thought it might be a bit early to be thinking about. Will keep working on other bits in the mean time :)
