### ISSUE TITLE
Enhancement: Add some more advertising :)

### ISSUE THREAD

**Issue by dumblob** [kisielk/vigo#6]
I couldn't find this repo although I tried really hard and even needed to bother guys from godit with a question about adding vi-like key-bindings and behavior :)

I would suggest to write to the README file at least (!) the keywords `text`, `editor`, `vim` (not only `vi`) and certainly ask guys from cat-v to add link to this repo to the page http://go-lang.cat-v.org/go-code to gain more attention. I guarantee, that there ale plenty other vi-fans which would surely want to try out (and improve) this editor!

**Comment by kisielk** [comment]
Hi :) One reason the project doesn't have a lot of advertising yet is that it's very much a work in progress. There's a lot of things broken, and many of the keybindings aren't actually implemented yet. I wouldn't really recommend anyone use this "editor" at this point.

**Comment by dumblob** [comment]
I know it, but despite of it I think at least the README and the repository description should be edited :-)

**Comment by kisielk** [comment]
Alright, added a small blurb to the README. Also added a link from https://code.google.com/p/go-wiki/wiki/Projects, which has replaced the cat-v.org list.
